// src/types/shipment.types.ts

export enum ShipmentStatus {
  CREATED = "CREATED",
  ASSIGNED = "ASSIGNED",
  PICKED_UP = "PICKED_UP",
  IN_TRANSIT = "IN_TRANSIT",
  DELAYED = "DELAYED",
  ARRIVED_HUB = "ARRIVED_HUB",
  OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
}

export enum ShipmentEventType {
  CREATED = "CREATED",

  ASSIGNED_DRIVER = "ASSIGNED_DRIVER",

  PICKED_UP = "PICKED_UP",

  IN_TRANSIT = "IN_TRANSIT",

  DELAYED = "DELAYED",

  ARRIVED_HUB = "ARRIVED_HUB",

  OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",

  DELIVERED = "DELIVERED",

  CANCELLED = "CANCELLED",
}