export enum UserRole {
    OWNER = "OWNER",
    ADMIN = "ADMIN",
    OPERATIONS_MANEGER = "OPERATIONS_MANAGER",
    WAREHOUSE_MANAGER = "WAREHOUSE_MANAGER",
    DRIVER = "DRIVER",
    CUSTOMER_SUPPORT = "CUSTOMER_SUPPORT",
}

